### ISSUE TITLE
ls-qpack-rs" requires a specific environment. When I try to use your project and build it with the MSVC compiler, I encounter an error: "error: failed to run custom build command for ls-qpack-sys v0.1.1 (https://github.com/BiagioFesta/ls-qpack-rs#866e740f)

### ISSUE THREAD

**Issue by redoriental** [BiagioFesta/ls-qpack-rs#2]

**Comment by BiagioFesta** [comment]
Can you please attach the entire error log?

**Comment by redoriental** [comment]
Checking libc v0.2.144
   Compiling bindgen v0.59.2
   Compiling ls-qpack-sys v0.1.1 (https://github.com/BiagioFesta/ls-qpack-rs#866e740f)
error: failed to run custom build command for `ls-qpack-sys v0.1.1 (https://github.com/BiagioFesta/ls-qpack-rs#866e740f)`
error: failed to run custom build command for `ls-qpack-sys v0.1.1 (https://github.com/BiagioFesta/ls-qpack-rs#866e740f)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `E:\untitled1\target\debug\build\ls-qpack-sys-ced565158fd145b6\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', D:\Rust-1.69\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\bindgen-0.59.2\src/lib.rs:2144:31
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:579
     1: core::panicking::panic_fmt
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:64
     2: core::result::unwrap_failed
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\result.rs:1750
     3: core::result::Result<T,E>::expect
     4: core::ops::function::FnOnce::call_once
     5: lazy_static::lazy::Lazy<T>::get::{{closure}}
     6: std::sync::once::Once::call_once::{{closure}}
     7: std::sys_common::once::queue::Once::call
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common\once\queue.rs:183
     8: std::sync::once::Once::call_once
     9: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
    10: <bindgen::BindgenOptions as core::default::Default>::default
    11: <bindgen::BindgenOptions as core::default::Default>::default
    12: bindgen::Builder::generate
    13: std::io::IoSlice::advance_slices
    14: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by BiagioFesta** [comment]
The relevant part is here:
```
 thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], 
```

It seems that `libclang` is not installed in the system where you are building the library.

`libclang` is provided by the *LLVM* project.

Try to install LLVM on Windows and try again.

---

There are several ways to install LLVM on Windows. 

For some versions, the LLVM Github repository already provides installer for windows, for instance the version 9.0.1:
https://github.com/llvm/llvm-project/releases/tag/llvmorg-9.0.1 (`LLVM-9.0.1-win64.exe`).

Of course if you are able to install a newer version is even better.

**Comment by redoriental** [comment]
error: failed to run custom build command for `ls-qpack-sys v0.1.1`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `C:\Users\redoriental\Downloads\test2\target\debug\build\ls-qpack-sys-ac765e8bd384709e\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "D:\\Rust-1.69\\registry\\src\\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\\ls-qpack-sys-0.1.1\\deps/ls-qpack" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DLSQPACK_BIN=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\redoriental\\Downloads\\test2\\target\\debug\\build\\ls-qpack-sys-ce5b6b6e2b0feb19\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"
  -- Compiler flags:  -nologo -MD -Brepro 
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/redoriental/Downloads/test2/target/debug/build/ls-qpack-sys-ce5b6b6e2b0feb19/out/build
  running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--parallel" "8"
  MSBuild version 17.3.1+2badb37d1 for .NET Framework
    ls-qpack.vcxproj -> C:\Users\redoriental\Downloads\test2\target\debug\build\ls-qpack-sys-ce5b6b6e2b0feb19\out\build\Debug\ls-qpack.lib
    -- Install configuration: "Debug"
    -- Up-to-date: C:/Users/redoriental/Downloads/test2/target/debug/build/ls-qpack-sys-ce5b6b6e2b0feb19/out/lib/ls-qpack.lib
    -- Up-to-date: C:/Users/redoriental/Downloads/test2/target/debug/build/ls-qpack-sys-ce5b6b6e2b0feb19/out/include/lsqpack.h
    -- Up-to-date: C:/Users/redoriental/Downloads/test2/target/debug/build/ls-qpack-sys-ce5b6b6e2b0feb19/out/include/lsxpack_header.h
    -- Up-to-date: C:/Users/redoriental/Downloads/test2/target/debug/build/ls-qpack-sys-ce5b6b6e2b0feb19/out/include/sys
    -- Up-to-date: C:/Users/redoriental/Downloads/test2/target/debug/build/ls-qpack-sys-ce5b6b6e2b0feb19/out/include/sys/queue.h
  cargo:root=C:\Users\redoriental\Downloads\test2\target\debug\build\ls-qpack-sys-ce5b6b6e2b0feb19\out
  cargo:rustc-link-search=native=C:\Users\redoriental\Downloads\test2\target\debug\build\ls-qpack-sys-ce5b6b6e2b0feb19\out\lib
  cargo:rustc-link-lib=static=ls-qpack
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LexError { span: Span }', D:\Rust-1.69\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\bindgen-0.59.2\src\codegen\mod.rs:3640:22
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/398fa2187c88de46c13c142f600064483a563c86/library\std\src\panicking.rs:593
     1: core::panicking::panic_fmt
               at /rustc/398fa2187c88de46c13c142f600064483a563c86/library\core\src\panicking.rs:67
     2: core::result::unwrap_failed
               at /rustc/398fa2187c88de46c13c142f600064483a563c86/library\core\src\result.rs:1651
     3: core::result::Result<T,E>::unwrap
     4: <bindgen::ir::ty::Type as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     5: <bindgen::ir::item::Item as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     6: <T as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     7: <bindgen::ir::ty::Type as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     8: <bindgen::ir::item::Item as bindgen::codegen::TryToRustTy>::try_to_rust_ty
     9: <T as bindgen::codegen::TryToRustTy>::try_to_rust_ty
    10: <T as bindgen::codegen::ToRustTyOrOpaque>::to_rust_ty_or_opaque
    11: <bindgen::ir::comp::FieldData as bindgen::codegen::FieldCodegen>::codegen
    12: <bindgen::ir::comp::Field as bindgen::codegen::FieldCodegen>::codegen
    13: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    14: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    15: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    16: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
    17: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    18: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    19: bindgen::codegen::codegen::{{closure}}
    20: bindgen::ir::context::BindgenContext::gen
    21: bindgen::codegen::codegen
    22: <bindgen::BindgenOptions as core::default::Default>::default
    23: bindgen::Builder::generate
    24: std::io::IoSlice::advance_slices
    25: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

I never thought I would get stuck on installing dependencies.

**Comment by redoriental** [comment]
If I can't use ls-qpack, I won't be able to use your wtransport. I want to know what other dependencies I need to install in order to successfully build ls-qpack. My Rust compiler is capable of compiling the quiche library.

**Comment by redoriental** [comment]
Your wtransport project is excellent, and I don't want to miss the opportunity to use it.

**Comment by redoriental** [comment]
TypeKind::Enum(..) => {
                let path = item.namespace_aware_canonical_path(ctx);
                let path = proc_macro2::TokenStream::from_str(&path.join("::"))
                    .unwrap(); //error
                Ok(quote!(#path))
            }

**Comment by BiagioFesta** [comment]
I understand.

Unfortunately, the error you are facing is not totally clear at the moment. It seems it comes from a dependency of this project, that is, [bindgen](https://github.com/rust-lang/rust-bindgen).

This crate (i.e., `ls-qpack-rs`) depends on its C-version and `bindgen` is the rust way to generate C-FFI.

Unfortunately it is harder to deal with dependencies in Windows I guess. However, I built this crate in Windows without any problem by just ensuring to had installed:
* Windows C compiler and runtimes (Windows Visual Studio)
* Rust windows toolchain (via rustup)
* LLVM (I've tested LLVM 9.0.1)
* CMake

And that is.

Can you please try to provide to me versions of such tools so I can try to reproduce and better understad why it is not building on your environment?

**Comment by BiagioFesta** [comment]
From the linked issue it seems it was indeed and env issue. I am going to close this
