### ISSUE TITLE
ls-qpack-sys depends on an older version of bindgen that is incompatible with clang 16

### ISSUE THREAD

**Issue by bugnano** [BiagioFesta/ls-qpack-rs#3]
With clang 16, the error is very similar to:

https://github.com/rust-lang/rust-bindgen/issues/2312

Given that bindgen has fixed the issue, it would be good to update the bindgen version dependency.

**Comment by BiagioFesta** [comment]
Dependencies' update has been merged (on `main` branch). Can you please check if that solved the issue?

Thanks for the report

**Comment by bugnano** [comment]
OK, I confirm that #4 solved this issue, thank you very much.
So now, it would be awesome to upgrade the ls-qpack dependency on wtransport, so that wtransport can build with clang 16 as well 😉

**Comment by BiagioFesta** [comment]
I agree. I will update as soon as possible.

Thank you
