### ISSUE TITLE
Doesn't build on arm64 linux

### ISSUE THREAD

**Issue by MOZGIII** [BiagioFesta/ls-qpack-rs#5]
Linux debian-4gb-fsn1-1 6.1.0-11-arm64 #1 SMP Debian 6.1.38-4 (2023-08-08) aarch64 GNU/Linux

```
error[E0308]: mismatched types
   --> /home/mozgiii/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ls-qpack-0.1.2/src/decoder.rs:374:31
    |
374 |             this.header.buf = this.decoding_buffer.as_mut_ptr() as *mut i8;
    |             ---------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut u8`, found `*mut i8`
    |             |
    |             expected due to the type of this binding
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

error[E0308]: mismatched types
   --> /home/mozgiii/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ls-qpack-0.1.2/src/header.rs:199:18
    |
199 |             buf: header.buffer.as_mut_ptr() as *mut i8,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut u8`, found `*mut i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`
```

I'm not sure why is this.

**Comment by BiagioFesta** [comment]
> I'm not sure why is this.

This comes from the FFI (i.e., the C bindings).

The variable `this.header.buf` has type [`c_char`](https://doc.rust-lang.org/std/ffi/type.c_char.html), that is, `char` type of C-language. 

Now, the C standard, does not guarantee the sign for the `char` type.

> char - type for character representation. Equivalent to either signed char or unsigned char (which one is implementation-defined and may be controlled by a compiler commandline switch), [...]

It means `char` is both valid to be `signed char` or `unsigned char`. It depends on the implementation.

On x86_64 char seems to be defined as signed (thus, `i8` in Rust), while it is *unsigned* on arm64 (this, `u8` in Rust)

**Comment by BiagioFesta** [comment]
@MOZGIII I don't have an easy way to test the patch on arm64 right now, if you have some spare time it would be great if you can see if you are able to compile it applying the patch: https://github.com/BiagioFesta/ls-qpack-rs/pull/6

Thank you :)
